### ISSUE TITLE
Call processQueue

### ISSUE THREAD

**Issue by carauzs** [thatisuday/ngDropzone#1]
Hello,
Is possible to call processQueue from controller?? 
Thanks.

**Comment by carauzs** [comment]
I got it.
Just save the instance from the init method.

``` javascript
var aux;
$scope.dzOptions = {
   ...
   init: function() {
      aux = this;
   }
};
$scope.submitDropzone = function () {
    aux.processQueue();
};
```

**Comment by thatisuday** [comment]
@Hicask Hi, Thanks for suggestion. I have drafted a new release https://github.com/thatisuday/ngDropzone/releases/tag/v1.0.3 for this functionality. 

Please read https://github.com/thatisuday/ngDropzone#enqueuing-file-uploads for implementation. 

This is the easiest and safest way. Also checkout [test.html](https://github.com/thatisuday/ngDropzone/blob/master/test/test.html) source code and [preview](https://htmlpreview.github.io/?https://github.com/thatisuday/ngDropzone/blob/master/test/test.html)

Let me know if this is working out for you. :)

**Comment by thatisuday** [comment]
@Hicask Now v1.0.4 supports all [Dropzone methods](http://www.dropzonejs.com/#dropzone-methods)
https://github.com/thatisuday/ngDropzone/releases/tag/v1.0.4

**Comment by carauzs** [comment]
I see, great I'll use it, thanks
