### ISSUE TITLE
changing url dinamically

### ISSUE THREAD

**Issue by jgpATs2w** [thatisuday/ngDropzone#15]
Thanks for this great plugin.
I've been exploring how to change the url (or any way to give some metadata to the file to upload).
By now, I've found this solution:
## HTML
```
  <ng-dropzone class="dropzone"
      dropzone="vm.dropzone" options="vm.dropzoneConfig" callbacks="vm.dzCallbacks" methods="vm.dzMethods">
    </ng-dropzone>
```

## angular module
  ```
vm.dropzoneConfig = {
    url:'http://url_by_default/',//need to put something here
    paramName : 'file',
    parallelUploads: 3,
    maxFileSize: 30
  }
  vm.dzCallbacks= {
    'processing': dzProcessing
  }
  function dzProcessing ( file ) {
    var dz = vm.dzMethods.getDropzone();
    dz.options.url='http://url_to_upload/'+vm.parameterOnUrl;
  }

```

  Please confirm me if there isn't any documented approach. If that is the case, I would ask you to include some instructions in the wiki examples.
Thanks!!

**Comment by thatisuday** [comment]
By far, I guess this is the only option. This plugin is just a directive of dropzone.js, so I am not sure if there is any other way to do this.

**Comment by RyanDawkins** [comment]
+1

I have a reference to dz in the controller of my component. You can also change the url with the reference you get in the $postLink event of your component.
