### ISSUE TITLE
Angular 4 support?

### ISSUE THREAD

**Issue by filflora** [thatisuday/ngDropzone#17]
Hi Uday,

do you plan to support Angular 4 too? Dropzone seems to be amazing and I'd like to use this module in my project. I was wondering if you have anything worked out for Angular4...

**Comment by thatisuday** [comment]
It's coming up...

**Comment by AmolST** [comment]
https://www.npmjs.com/package/angular-file-dropzone

**Comment by iamjsmith** [comment]
Any news on this yet?

**Comment by thatisuday** [comment]
Sorry man. Too busy. :(


--------------

Respectfully,
*Uday Hiwarale*
Full Stack Developer
New Delhi, India
Ph. +91-9650913753
Website : http://thatisuday.com, http://gitmeet.com

**Comment by thatisuday** [comment]
@iamjsmith @MchlFil Perhaps try this https://github.com/zefoy/ngx-dropzone-wrapper
