### ISSUE TITLE
sending event does not append anything to formData

### ISSUE THREAD

**Issue by mozaffar** [thatisuday/ngDropzone#19]
I have some simple variables which have data. When I append them to formData in sending event nothing will be passed to data. 

`'sending': function (file, xhr, formData){
formData.append("image", file);
formData.append("alias", vm.category.alias);
formData.append("name", vm.category.name);
formData.append("parent_id", vm.category.parent_id);
formData.append("description", vm.category.description);
formData.append("published", vm.category.published);
formData.append("_token", token);
console.log(vm.category); // This returns all values
console.log(formData); // This returns nothing
                }`

when I log my vm.category it shows all data but there is no data appended to formData.

What shall I do?

**Comment by simon-lang** [comment]
@mozaffar - did you figure this out? I'm having the same issue.

**Comment by mozaffar** [comment]
ha ha ha ha
Be sure that they are appended but you cannot see them by simple `console.log` command. Do not pay attention to it. You can check them in sending data to server
