### ISSUE TITLE
Add wiki

### ISSUE THREAD

**Issue by frostbitten** [thatisuday/ngDropzone#2]
Hi,

First of all, thanks for this great directive!

I would like to add some examples I've made and the wiki would seem a good spot. Can this be enabled for this repo?

Thanks again!

**Comment by thatisuday** [comment]
@frostbitten Hi, thanks for feedback. I am new in the world of angular and github. Tell me what you need.

**Comment by frostbitten** [comment]
Just noticed this. Thanks for adding! I am also new to both. Hoping to send an example for use on the wiki when I get the time.

**Comment by thatisuday** [comment]
@frostbitten Can you work on button only dropzone. The one I made is just a hack but not reliable and optimized functionality. What required is that user should assign dropzone instance to a button and can upload file(s) without actually showing preview thumbnails. Technically, only `hidden file input` **click** event is registered to a button and preview pane is not visible or never created. 

![drawing](https://cloud.githubusercontent.com/assets/5711821/15384360/a267ef4e-1db7-11e6-8d26-0a87066e3d0b.png)
