### ISSUE TITLE
Module 'thatisuday.dropzone' is not available!

### ISSUE THREAD

**Issue by aranderia** [thatisuday/ngDropzone#20]
Hi, 

I am trying to integrate dropzone.js in my angular form. When I configure the module "angular.module("myApp", ["thatisuday.dropzone"])" is throws the following error..

Uncaught Error: [$injector:modulerr] Failed to instantiate module AdaptiveAlgoApp due to:
Error: [$injector:modulerr] Failed to instantiate module thatisuday.dropzone due to:
Error: [$injector:nomod] Module 'thatisuday.dropzone' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Please let me know what I mistake I am doing. Thanks!

**Comment by thatisuday** [comment]
This shouldn't happen. Check if you have loaded js files from ngdropzone as well as dropzone.js

**Comment by aranderia** [comment]
I configured ngdropzone using npm. Do i have to include the js files manually as well? Thanks!

**Comment by thatisuday** [comment]
I have never tested this module using npm but it's working for other people. I would recommend to use bower for now. I am working on angular 4 (prev. 2) version of this module now..

**Comment by aranderia** [comment]
Hi Uday,

I have followed the steps given and have included dropzone and ng-dropzone js as well as css files. The console does not show any error but the page goes blank. Any idea? Thanks!
