### ISSUE TITLE
Help - Dropzone is not defined (using ES6)

### ISSUE THREAD

**Issue by Luddinus** [thatisuday/ngDropzone#3]
Hi,

I'm using ES6 Syntax and I want to use this package.

I cannot use the "import" syntax when using ES6 Syntax because it gives the error of the title (Dropzone is not defined).

What can  I do?

Thx.

**Comment by thatisuday** [comment]
Not familiar with ES6 yet but I guess you did not load dropzonejs file before ng-dropzone. Download from http://dropzonejs.com

**Comment by Luddinus** [comment]
Well, fixed with this:

```
import Dropzone from 'dropzone';
import 'dropzone/dist/dropzone.css';
import 'ngdropzone/extra/ngDzBeautify.css';
import 'ngdropzone';

// I forgot this
window.Dropzone = Dropzone;
window.Dropzone.autoDiscover = false;
```

**Comment by thatisuday** [comment]
Great.
