### ISSUE TITLE
Angular 1.5 Component

### ISSUE THREAD

**Issue by sicollins** [thatisuday/ngDropzone#4]
Great plugin.

I'm using it in an Angular 1.5 app built with component architecture.

Everything is working just fine but I'm struggling to work out how to get a ref of the ng-dropzone object in my component controller, in order to call the getDropzone() method.

`<div class="dropzone" options="vm.dzOptions" callbacks="vm.dzCallbacks" methods="vm.dzMethods" ng-dropzone></div>`

I need to be able to populate the dropzone with files which already exists on the server.

Any help much appreciated.

**Comment by sicollins** [comment]
The solution for anyone else having this issue is to use the $postLink lifecycle hook.

You can do the following in your component controller function:

`vm.$postLink = function () {
    var dz = vm.dzMethods.getDropzone();
    console.log(dz);
};`

Would be interested to know if anyone had done this differently?

**Comment by thatisuday** [comment]
@sicollins Is it fixed? If not, can you share some code?

**Comment by sicollins** [comment]
@thatisuday yes I am able to call getDropzone() ok using the code I posted above but would be interested to hear if you or anyone else has used a different approach in Angular 1.5?

**Comment by thatisuday** [comment]
Glad that is it working. I am not into _components_ that much, but sure will look into it. I will keep this issue open until we find a better solution.

**Comment by JulienBourgain** [comment]
@sicollins 

```
angular.componant(<name>, {
  templateUrl: <url>.html,
  controller: function () {
     vm.$onInit = function() {
       var dz = vm.dzMethods.getDropzone(); 
       console.log(dz);
     }
   }
}
```

the $onInit function on the component is here for that ;)

I have put a '+1' for the "populate the dropzone" part of your issue :p

**Comment by sicollins** [comment]
@JulienBourgain tried that first but it doesn't work because $onInit is called before the DOM has been linked.

**Comment by thatisuday** [comment]
@sicollins Can you please share your template

**Comment by thatisuday** [comment]
@JulienBourgain Can you share your html so that I can work around `require`?

**Comment by thatisuday** [comment]
This will help people with same problem.

https://github.com/thatisuday/ng-dropzone/wiki/Working-with-angular-1.5-Component
