### ISSUE TITLE
How to show files already stored on server?

### ISSUE THREAD

**Issue by essivision** [thatisuday/ngDropzone#5]
Hi,
I want to show files already stored on server with `dropzone.emit` mockfile for call the event handlers addedfile and thumbnail to draw the preview.

[https://github.com/enyo/dropzone/wiki/FAQ#how-to-show-files-already-stored-on-server](https://github.com/enyo/dropzone/wiki/FAQ#how-to-show-files-already-stored-on-server)

Thanks

**Comment by thatisuday** [comment]
@essivision I will look into it. Anything you tried so far? What's not working out?

**Comment by sicollins** [comment]
@essivision @thatisuday this is exactly what I was trying to do when I raised this https://github.com/thatisuday/ng-dropzone/issues/4 yesterday.

Hope this helps anyway. Once you've got a ref to the dropzone object using the getDropzone() method you just need to loop over your files and push the mockFile in using the code from the link you posted.

```
var dz = vm.dzMethods.getDropzone();
 _.each(vm.files, function (file) {                        
    var mockFile = { name: "Filename", size: 12345 };
    // Call the default addedfile event handler
    dz.emit("addedfile", mockFile);
    // And optionally show the thumbnail of the file:
    dz.emit("thumbnail", mockFile, "/image/url");
    // Or if the file on your server is not yet in the right
    // size, you can let Dropzone download and resize it
    // callback and crossOrigin are optional.
    dz.createThumbnailFromUrl(file, file.imageUrl);

    // Make sure that there is no progress bar, etc...
    dz.emit("complete", mockFile);

    // If you use the maxFiles option, make sure you adjust it to the correct amount:
    var existingFileCount = 1; // The number of files already uploaded
    dz.options.maxFiles = dz.options.maxFiles - existingFileCount;
});
```

In my case vm is just the scope of my 1.5 component and vm.files is an array I pass in from the parent component in the same way you pass an array to a directive.

**Comment by thatisuday** [comment]
@essivision Not recommend but still, here it is.

https://github.com/thatisuday/ng-dropzone/wiki/Mock-files-(already-uploaded)-from-server-into-dropzone

Please read precautions.
