### ISSUE TITLE
How is the Dropzone variable defined?

### ISSUE THREAD

**Issue by moxious** [thatisuday/ngDropzone#6]
I'm in an es6 environment where multiple scripts are packaged together; inside of the component that needs to use ng-dropzone, I inject the component but get the error:

`angular.js:13920 ReferenceError: Dropzone is not defined`

This is happening in the link function of the provided directive.

The controller on that component does this:

```
const Dropzone = require('dropzone');
import 'ngdropzone';
```

This is probably not seen by the angular directive, question is what's being missed here?

**Comment by thatisuday** [comment]
Duplicate? https://github.com/thatisuday/ng-dropzone/issues/3
