### ISSUE TITLE
Interceptors cannot catch the upload XHR

### ISSUE THREAD

**Issue by paambaati** [thatisuday/ngDropzone#8]
I use [satellizer](https://github.com/sahat/satellizer) by @sahat, which is an authentication library that automatically injects an interceptor that attaches `Authorization` headers to all outgoing requests. It doesn't seem to work with ng-dropzone though, and currently I am working around it by setting the headers manually via options.

But I'm surprised the interceptor didn't catch it. Is that because dropzone uses raw XHR? Would it be possible to wrap them with a `$http`?

**Comment by thatisuday** [comment]
This seems to be a `dropzone` problem rather than of `ng-dropzone`. But how you are implementing `satellizer` with ng-dropzone and for what purpose?

**Comment by paambaati** [comment]
I use satellizer on a SPA that makes a lot of API calls, and I use `satellizer` to handle automatically adding Authorisation headers to all thlse API requests. I wanted to upload a file using `ng-dropzone`, and realized that the upload call alone doesn't have the header attached.

**Comment by sahat** [comment]
@paambaati You should be able to pass the `headers` option with `Authorization: Bearer <Token>` via setOptions. (Where `<Token>` is your JWT from Local Storage)

dropzone.js: http://www.dropzonejs.com/#config-headers

ng-dropzone: https://github.com/thatisuday/ng-dropzone#optional

**Comment by paambaati** [comment]
@sahat Thanks for chiming in! I'm already doing that. I was just wondering if it was possible to not have to do that and get the component to do it automatically.

**Comment by sahat** [comment]
Yeah I doubt it. 

ng-dropzone is just a simple directive wrapper. Angular may not even aware of the outgoing HTTP request by dropzone.js.

**Comment by thatisuday** [comment]
@paambaati I think @sahat explained it all. ng-dropzone is just wrapper around dropzone. They might be using XMLHttpRequest object to transmit data, hence no way to intercept the request from ng-dropzone. But as @sahat explained, you can config you app to implement custom headers for all your app requests.
