### ISSUE TITLE
Not able to override default options

### ISSUE THREAD

**Issue by alpacaData** [thatisuday/ngDropzone#9]
hello i'm using your ng-dropzone :
**JS**
```
window.Dropzone = Dropzone;
            window.Dropzone.autoDiscover = false;
            $scope.dropzoneOps={ url:"http://timeline.dev/index.php/upload",
                paramName: "file", // The name that will be used to transfer the file
                maxFilesize: 50, // MB
                addRemoveLinks: false,
                uploadMultiple: true,
                parallelUploads: 100,
                maxFiles: 100,
                autoProcessQueue: false};
```
**angular js module :** `
var timeline = angular.module('timeline', ['ngRoute','thatisuday.dropzone']).controller('mainCtrl', ['$scope', '$http', '$location', '$timeout', function ($scope, $http, $location, $timeout) {`

**html**
```
<form action="http://timeline.dev/index.php/upload" class="dropzone" id="my-dropzone" enctype="multipart/form-data">
        </form>
```

I'm not able to override the options...what could be ?

**Comment by alpacaData** [comment]
@thatisuday

**Comment by thatisuday** [comment]
@federicoco First of all, dropzone has nothing to do with form. Anyway, follow common examples https://github.com/thatisuday/ng-dropzone/wiki/Common-Examples to understand how it works.

**Comment by alpacaData** [comment]
hello, sorry for yesterday,
First of all , I've followed your common examples
`<ng-dropzone action="http://timeline.dev/index.php/upload" id="dropzone1"  class="dropzone" options="dzOptions" callbacks="dzCallbacks" enctype="multipart/form-data"></ng-dropzone>`

**Javascript**

```
    $(function() {
                $scope.dzOptions = {
                    paramName : 'file',
                    dictDefaultMessage : 'Add files to show dropzone methods (few)',
                    autoProcessQueue:false,
                    url:"http://timeline.dev/index.php/upload",
                    maxFilesize : '10'
                };
            });
```

What fix would you suggest ?

![ngdropzone](https://cloud.githubusercontent.com/assets/22914696/20381582/49a284ac-aca8-11e6-9b7d-d19582a0c65a.jpg)

**Comment by thatisuday** [comment]
@federicoco Are you facing any issues now?

**Comment by alpacaData** [comment]
I've managed to resolve the issue : 
i've just put the `$scope.dzOptions` in the init of my angular module (the first line where the module starts to execute the data).
For everyone that has problems with dropzone or ng-dropzone and you're using angular modules,follow the readme of ng-dropzone and in your controller put this

```
$scope.init = function ()          //equivalent of $(function) or Document.onLoad etc.etc. 
{
    //put DzOptions /callbacks /methods here
}; 
```
